accounts/urls.py
# accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('topics', views.add_topic, name='add_topic'),
    path('topics/<uuid:pk>/', views.TopicView.as_view(), name='topics'),
    path('topics/<uuid:topic_id>/comment/', views.add_comment, name='add_comment'),

]

lending_loop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView 

urlpatterns = [
    path('', include('forum.urls')), # new
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('forum/', include('forum.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

forum/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title_text

class Comment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.comment_text

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

forum/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.utils import timezone
from django.urls import reverse
from django.views import generic

from .models import Topic, Comment
# Create your views here.
class IndexView(generic.ListView):
    template_name = 'forum/index.html'
    context_object_name = 'latest_topic_list'

    def get_queryset(self):
        return Topic.objects.order_by('-pub_date')[:5]

class TopicView(generic.DetailView):
    model = Topic
    template_name = 'forum/topic.html'

def add_topic(request):
    if (request.POST['title']):
        topic = Topic(
            pub_date=timezone.now(),
            title_text=request.POST['title'],
            author_id=request.user.id
        )
        topic.save()
        return HttpResponseRedirect(reverse('forum:index'))

def comments(request, topic_id, comment_id):
    return HttpResponse("You're looking at topic %s and comment %s" % topic_id, comment_id)

def add_comment(request, topic_id):
    if (request.POST['comment']):
        comment = Comment(
            topic_id=topic_id,
            pub_date=timezone.now(),
            comment_text=request.POST['comment'],
            author_id=request.user.id
        )
        comment.save()
        return HttpResponseRedirect(reverse('forum:topics', args=(topic_id,)))

forum/templates/forum/index.html
{% extends 'base.html' %}

{% block content %}
{% if latest_topic_list %}
    <ul class="list-group">
    {% for topic in latest_topic_list %}
        <li class="list-group-item">
            <h3><a href="{% url 'forum:topics' topic.id %}">{{ topic.title_text }}</a> <small class="text-muted">{{ topic.author.username }} {{ topic.pub_date | date:"M d, Y" }}</small></h3></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No topics are available.</p>
{% endif %}

<hr class="mt-0 mb-4">
{% if user.is_authenticated %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'forum:add_topic' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <input class="form-control" type="text" name="title" id="title" value="" placeholder="Title ...">
    </div>
    <input class="btn btn-success" type="submit" value="Add new topic">
</form>
{% endif %}


{% endblock %}

forum/templates/forum/topic.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-2">
        <a class="btn btn-primary" href="{% url 'forum:index' %}" role="button">Back</a>
    </div>
    <div class="col-8">
        <h1>Topic {{ topic.title_text }}</h1>
    </div>
    <div class="col-12">
        <ul class="list-group">
            {% for comment in topic.comment_set.all %}
                <li class="list-group-item">{{ comment.comment_text }} - {{ comment.pub_date | date:"M d, Y" }} <br/> {{ comment.author.username }}</li>
            {% endfor %}
        </ul>

        <hr class="mt-0 mb-4">

        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <form action="{% url 'forum:add_comment' topic.id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" type="text" name="comment" id="comment" value="" placeholder="Your comment ...">
            </div>
            <input type="submit" class="btn btn-success" value="Add new comment">
        </form>
    </div>
</div>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load sass_tags %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:100,100italic,200,300,regular,italic,500,600,600italic,700,800,900" media="all">
    <link rel="stylesheet" type="text/css" href="{% sass_src 'forum/style.scss' %}">
    <title>Lending Looop</title>
</head>

<body>
    <nav class="navbar navbar-expand-md fixed-top">
        <a class="navbar-brand" href="{% url 'forum:index' %}">
            <img src="/static/forum/img/logo.svg" width="30" height="30" class="d-inline-block align-top" alt="">
            Lending Loop
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                
            </ul>
            <span class="navbar-text navbar-user">
                {% if user.is_authenticated %}
                <ul>
                    <li class="navbar-user__username">
                        Hi {{ user.username }}!
                    </li>
                    <li>
                        <a class="btn btn-dark" href="{% url 'logout' %}">Logout</a>
                    </li>
                </ul>
                {% else %}
                    <ul>
                        <li>
                            <a class="btn btn-dark" href="{% url 'signup' %}">Sign up</a>
                        </li>
                        <li>
                            <a class="btn btn-primary" href="{% url 'login' %}">login</a>
                        </li>
                    </ul>
                {% endif %}
            </span>
        </div>
    </nav>
    <main role="main" class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </main>
</body>

</html>

templates/home.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

templates/signup.html
<!-- templates/signup.html -->
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_username">Username</label>
            <input type="text" name="username" autofocus="" class="form-control" maxlength="150" id="id_username" placeholder="Enter username">
            <small id="usernameHelp" class="form-text text-muted">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small>
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" name="password1" required="" class="form-control" id="exampleInputPassword1" placeholder="Password">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword2">Password confirmation</label>
            <input type="password" name="password2" required="" class="form-control" id="exampleInputPassword2" placeholder="Password">
            <small id="passwordConfirmationHelp" class="form-text text-muted">Enter the same password as before, for verification.</small>
        </div>
        <button type="submit" class="btn btn-primary">Sign up</button>
    </form>
{% endblock %}